package_mappings:
  - core-: core_elements
  - paper-: paper_elements
  - web-animations: core_elements
files_to_generate:
  - material-card/material-card.html
stubs_to_generate:
  paper_elements:
    - "paper-shadow/paper-shadow.html"
